### ISSUE TITLE
clickfix window stuck while dragging

### ISSUE THREAD

**Issue by rikdol** [CemraJC/clickfix#18]
Just installed clickfix under Windows 10 [Version 10.0.19041.630] x64

i noticed when i tried to drag the clickfix window it sticks to the mouse pointer. and clicking again doesn't release it. 

hope it's not a singular issue on my end.

**regarding the fix itself:**
Setting the 'pressure' at 100 ms seemed to have solved it for now. Not quite sure whether it's a hardware issue or not.

it seems however that I sometimes double-click faster than 100ms. so I need to slow down a bit when that occurs. :)

Thanks for this solution.

**Comment by CemraJC** [comment]
Hello! This can happen when a mouse has gone particularly bad - the mousedown event will fire, but the mouseup event is lost, fighting with the hardware even. This makes the computer think that there hasn't been a mouse up, because of the imbalance.

Really sorry about this, there's not much I can do - hopefully the slow double-click is bearable for now!

**Comment by rikdol** [comment]
Thanks for the update Cemra.
