### ISSUE TITLE
PSA: banned from CoD Vanguard

### ISSUE THREAD

**Issue by alecaputo13** [CemraJC/clickfix#23]
It's more just a warning than an issue. Activision permanently banned me from their game because of this little software.
So if there are any gamers here, be careful and close the program before start playing. 

I would also suggest to put a disclaimer in the readme or a the first start of this software.

I'm not, by any means, blaming this script, the only issue here is the Activision-Blizzard's cr@p anti-cheat system (:

**Comment by realdomdom** [comment]
@alecaputo13 This may have been due to the pre-compiled version of this script available for download on github using a so-called PE packer, a program that compresses the executable file and decompresses it upon execution. If you upload the file to [virustotal.com](virustotal.com)  and then compile the script by yourself and upload your own version without any compression, you will find, that by doing just that, the number antivirus vendors falsely detecting this as a malicious file will have been reduced to 3. This is because by merely using such a compression, many antivirus programs flag such an executable by default. 

Though it is also not unlikely the anti-cheat was triggered by the mere presence of the hook or the discrepancy between the hardware events and the clicks executed in software. 

Nevertheless, it would be far easier to just analyse the file for a packer (or the signature thereof) and conclude it's malicious. 

You're absolutely right that anti-cheat systems get out of hand. Then again, the methods of cheating are getting out of hand too.
