### ISSUE TITLE
Binary detected as trojan by Windows Defender

### ISSUE THREAD

**Issue by NNpranav** [CemraJC/clickfix#8]
Windows Defender Threats Definition Version: 1.261.1605.0

Downloaded the latest release from here: https://github.com/cemrajc/clickfix/releases/latest

Upon extraction, Windows Defender presents a warning and removes the binary. Either it's a false positive (perhaps because you're using some autohotkey-type tool to generate the executable that is getting flagged) or the release is compromised for whatever reason.

![clickfix](https://user-images.githubusercontent.com/30431653/36639908-f15927da-1a3b-11e8-9095-6bb5e82537df.png)

**Comment by CemraJC** [comment]
As long as you're downloading from Github through an https connection (as that link will do for you) then you should be all good. Unfortunately, because ClickFix esentially hijacks the mouse, these sorts of false positives are going to happen.

If you want, the code for AHK is available for you to read (and confirm is non-malicious nature). Additionally, it's fairly straight forward to complile this code yourself, so I would recommend this if you don't trust the downloaded version.

Good luck! 😄
